// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetCare.API.Data;

#nullable disable

namespace PetCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309074643_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetCare.API.Models.Entities.Cita", b =>
                {
                    b.Property<Guid>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdClinica")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdMascota")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdVeterinario")
                        .HasColumnType("uuid");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCita");

                    b.HasIndex("IdClinica");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Clinica", b =>
                {
                    b.Property<Guid>("IdClinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdClinica");

                    b.ToTable("clinicas");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Consulta", b =>
                {
                    b.Property<Guid>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCita")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("consultas");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Mascota", b =>
                {
                    b.Property<Guid>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdUsuario");

                    b.ToTable("mascotas");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "admin"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "veterinario"
                        },
                        new
                        {
                            IdRol = 3,
                            NombreRol = "cliente"
                        });
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Tratamiento", b =>
                {
                    b.Property<Guid>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IdConsulta")
                        .HasColumnType("uuid");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Plazo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdTratamiento");

                    b.HasIndex("IdConsulta");

                    b.ToTable("tratamientos");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Cita", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Clinica", "Clinica")
                        .WithMany("Citas")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.Entities.Mascota", "Mascota")
                        .WithMany("Citas")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("Citas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.Entities.Usuario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Mascota");

                    b.Navigation("Usuario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Consulta", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Cita", "Cita")
                        .WithOne("Consulta")
                        .HasForeignKey("PetCare.API.Models.Entities.Consulta", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Mascota", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Tratamiento", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Consulta", "Consulta")
                        .WithMany("Tratamientos")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Usuario", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Clinica", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Consulta", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Mascota", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
