// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetCare.API.Data;

#nullable disable

namespace PetCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410182945_SyncCascadeState")]
    partial class SyncCascadeState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {


        }
    }
}
