// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetCare.API.Data;

#nullable disable

namespace PetCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetCare.API.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("id_appointment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("appointment_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("cost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("id_clinic")
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_pet")
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_user")
                        .HasColumnType("uuid");

                    b.Property<Guid>("id_veterinarian")
                        .HasColumnType("uuid");

                    b.Property<string>("service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id_appointment");

                    b.HasIndex("id_clinic");

                    b.HasIndex("id_pet");

                    b.HasIndex("id_user");

                    b.HasIndex("id_veterinarian");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Clinic", b =>
                {
                    b.Property<Guid>("id_clinic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_clinic");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Consultation", b =>
                {
                    b.Property<Guid>("id_consultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("consultation_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("id_appointment")
                        .HasColumnType("uuid");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_consultation");

                    b.HasIndex("id_appointment")
                        .IsUnique();

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Pet", b =>
                {
                    b.Property<Guid>("id_pet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.Property<string>("breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("id_user")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("weight")
                        .HasColumnType("numeric");

                    b.HasKey("id_pet");

                    b.HasIndex("id_user");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_role"));

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id_role");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            id_role = 1,
                            role_name = "admin"
                        },
                        new
                        {
                            id_role = 2,
                            role_name = "veterinario"
                        },
                        new
                        {
                            id_role = 3,
                            role_name = "cliente"
                        });
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Treatment", b =>
                {
                    b.Property<Guid>("treatment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("cost")
                        .HasColumnType("numeric");

                    b.Property<string>("dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("id_consultation")
                        .HasColumnType("uuid");

                    b.Property<string>("medication")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("treatment_id");

                    b.HasIndex("id_consultation");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("id_role")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_user");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("id_role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Appointment", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Clinic", "Clinic")
                        .WithMany("Appointment")
                        .HasForeignKey("id_clinic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.Entities.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("id_pet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCare.API.Models.Entities.User", "veterinarian")
                        .WithMany()
                        .HasForeignKey("id_veterinarian")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Pet");

                    b.Navigation("User");

                    b.Navigation("veterinarian");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Consultation", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Appointment", "Appointments")
                        .WithOne("Consultations")
                        .HasForeignKey("PetCare.API.Models.Entities.Consultation", "id_appointment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Pet", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.User", "user")
                        .WithMany("pets")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Treatment", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Consultation", "Consultations")
                        .WithMany("Treatments")
                        .HasForeignKey("id_consultation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.User", b =>
                {
                    b.HasOne("PetCare.API.Models.Entities.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Appointment", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Clinic", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Consultation", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Pet", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PetCare.API.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("pets");
                });
#pragma warning restore 612, 618
        }
    }
}
